[package]
name = "uring_bpm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
tokio = { version = "1.36.0", features = ["rt", "macros"] }
tokio-uring = "0.4.0"
